        // Array of search terms
        const searchTerms = [            "AZUL",
        "OLMECA",
        "OLMECA",
        "CAMINO",
        "AZUL",
        "CAMINO",
        " BAILEYS",
        "SMIRNOFF ICE",
        "DESPERADOS",
        "STAR-RADLER",
        "FLYING FISH",
        "HENNESSY XO",
        "MARTEL VSOP",
        "HENNESSY VSOP",
        "REMY MARTINS",
        "HENNESSY VS",
        "MARTEL VS",
        "FOUR COUSIN",
        "BARON",
        "4TH STREET",
        "CIROC",
        "BIG STOUT",
        "HEINEKEN",
        "BUDWEISER",
        "33",
        "TROPHY",
        "TIGER",
        "GULDER",
        "TROPHY/S",
        "LEGEND",
        "GLENFIDDICH 18Y",
        "GLENFIDDICH 15Y",
        "JAMESON BLACK",
        "JACK DANIEL",
        "JAMESON WHKY",
        "BLACK LABEL",
        "RED LABEL",
        "CAMPARI(BIG)",
        "CRANBERRY",
        "HOLLANDIA",
        "CHIVITA",
        "POWER HORSE",
        "RED BULL",
        "MONSTER",
        "BULLET",
        "ZAG",
        "AMBER",
        "CLIMAX",
        "CONFAM",
        "ODOGWU",
        "ACTION/B",
        "ORIGIN",
        "HENNESSY SHOT",
        "J/DANIELS SHOT",
        "TEQUILA SHOT",
        "BACARDI SHOT",
        "JAMESON SHOT",
        "CIROC SHOT",
        "SMIRNOFF/SHOT",
        "MALTINA",
        "MALTA/G",
        "COKE",
        "FAYROUZ",
        "WATER",
        "DON PERIGNON",
        "MOET ROSE",
        "BELAIRE ROSE",
        "ANDRE ROSE",
        "SHISHA (SINGLE H)",
        "SHISHA (DOUBLE H)",
        "GRILLED CROCKER (E/L)",
        "GRILLED CROCKER (M)",
        "CHICKEN SHAWARMA",
        "GRILLED CATFISH",
        "ASUN",
        "EXTRA YAM",
        "EXTRA SALAD",
        "EXTRA CHIPS",
        "WHITE RICE",
        "JOLLOF RICE",
        "FRIED RICE",
        "MEXICAN RICE",
        "CHINESE RICE",
        "NATIVE RICE",
        "OFADA RICE & SAUCE",
        "COCONUT RICE & SHRIMP",
        "EXTRA CHIPS",
        "PEPPERED CHICKEN",
        "PEPPERED TURKEY",
        "PEPPERED GIZZARD",
        "PEPPERED BEEF",
        "PEPPERED ASSORTED",
        "PEPPERED GOATMEAT",
        "PEPPERED CROCKER 1/2",
        "PEPPERED CROAKER (FULL)",
        "CHICKEN PEPPER SOUP",
        "TURKEY PEPPER SOUP",
        "GOAT MEAT PEPPER SOUP",
        "ASSORTED PEPPER SOUP",
        "CATFISH PEPPER SOUP (1/2)",
        "CATFISH PEPPER SOUP (FULL)",
        "CROCKER PEPPER SOUP (1/2)",
        "CROCKER PEPPER SOUP (FULL)",
        "CHICKEN & CHIPS",
        "TURKEY & CHIPS",
        "BEEF BURGER & CHIPS",
        "CHICKEN BURGER & CHIPS",
        "PASTA ALIO",
        "PASTA RIGATONI",
        "PASTA ARABIATA & CHICKEN",
        "PASTA BOLOGNESE",
        "SEAFOOD PASTA",
        "SMALL CHOPS",
        "SKEWERED PRAWN",
        "JUICY CRAB",
        "SEAFOOD COMBO",
        "AFANG SOUP",
        "BANGA SOUP",
        "EDIKAIKONG SOUP",
        "EFO RIRO",
        "EGUSI SOUP",
        "OGBONOR",
        "OKRO",
        "FISHERMAN SOUP",
        "SEAFOOD OKRA",
        "NATIVE SOUP",
        "AMALA",
        "POUNDO",
        "EBA",
        "SEMO",
        "WHEAT",
        "ISI-EWU",
        "NKWOBI",
        "PLANTAIN PORRIDGE",
        "YAM PORRIDGE",
        "EGG SAUCE & YAM",
        "EGG SAUCE PLANTAIN",
        "ENGLISH BREAKFAST",
        "BARBECUE CHICKEN (1/2)",
        "BARBECUE CHICKEN (FULL)",
        "SPRING ROLL & SAMOSA",
        "PARFAIT",
        "VIRGIN MOJITO",
        "CRANBERRY SPECIAL",
        "COCOPINE SPECIAL",
        "CHAPMAN",
        "LEMONADE",
        "STRAWBERRY COLADA",
        "BANANA COLADA",
        "VIRGIN COLADA",
        "PINA COLADA",
        "INCREDIBLE BERRY",
        "STRAWBERRY EXTREME",
        "TEQUILA SUNRISE",
        "SEX ON THE BEACH",
        "MOJITO",
        "LONG ISLAND ICE TEA",
        "LONG ISLAND ELECTRIC",
        "LASTMAN STANDING",
        "STRAWBERRY MARGARITA",
        "MANGO MARGARITA",
        "SUNNY ISLAND",
        "WHISKEY SOUR",
        "TEQUILA SHOTS",
        "MALIFICIENT",
        "KARDELEXX SPECIAL",
        "HOUSE SPECIAL",
        "BANANA",
        "STRAWBERRY",
        "CHOCOLATE",
        "VANILLA",
        "MANGO"];

        // Function to open a new tab with Google image search for each term
        function openGoogleImageSearch(term) {
            const searchUrl = `https://www.google.com/search?q=${term}&tbm=isch`;
            window.open(searchUrl, '_blank');
        }

        // Loop through the array and open a new tab for each search term
        searchTerms.forEach(term => {
            openGoogleImageSearch(term);
        });