CREATE TABLE Orders (
  id INT AUTO_INCREMENT PRIMARY KEY ,
  saleslog JSON,
  Sid TEXT,
  Categories JSON,
  products JSON,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE Orders AUTO_INCREMENT=1;

CREATE TABLE Order (
  id INT AUTO_INCREMENT PRIMARY KEY ,
  saleslog JSON,
  Sid TEXT,
  Categories JSON,
  products JSON,
  Pid TEXT,
  Cid TEXT,
  Name VARCHAR(255),
  Qty BIGINT,
  Unit BIGINT,
  Total DOUBLE,
  `Table` VARCHAR(255),
  Server VARCHAR(255),
  date_created TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE Orders AUTO_INCREMENT=1;


CREATE TABLE Sales (
  id INT AUTO_INCREMENT PRIMARY KEY ,
  Pid TEXT,
  Cid TEXT,
  Name VARCHAR(255),
  Qty BIGINT,
  Unit BIGINT,
  Total DOUBLE,
  `Table` VARCHAR(255),
  Server VARCHAR(255),
  date_created TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE Sales AUTO_INCREMENT=1;


CREATE TABLE Staffs (
  id INT AUTO_INCREMENT PRIMARY KEY ,
  Name VARCHAR(255),
  Pin BIGINT,
  Phone VARCHAR(255),
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE Staffs AUTO_INCREMENT=1;

CREATE TABLE `Products` (
  id INT AUTO_INCREMENT PRIMARY KEY ,
  -- `id` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `Name` varchar(255) DEFAULT NULL,
  `Price` decimal(10,2) DEFAULT NULL,
  `Category` varchar(50) DEFAULT NULL,
  `Stock` int DEFAULT NULL,
  `Tag` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE Products AUTO_INCREMENT=1;

ALTER TABLE sales
ADD COLUMN Status VARCHAR(255) DEFAULT 'NOTCLEARED';
